### ISSUE TITLE
This isnt an issue. I just wanted to let you know how amazing this project is

### ISSUE THREAD

**Issue by Ubuntufanboy** [gavin-lb/image-to-prime#1]
There is a js alternative that does not run on machine and I tried to get it working for hours. I figured i'd just look for some alternatives. I found this repo and I was super skeptical at first but once I tried it out... I was amazed. Not only was I able to use it, but It was written well enough for me to modify the source code to my liking. I wish I could this repo 100 stars because I would.

# THANK YOU FOR SUCH AN AMAZING REPO

**Comment by gavin-lb** [comment]
Hi, thanks for the kind words.
